### ISSUE TITLE
new versions not launching and throwing errors

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy-Standalone-OSX#1]
I am getting errors when trying to launch the newest releases of the compiled pmag_gui and magic_gui. Here are the errors that are getting printed to the console:
```
1/26/16 9:36:14.546 PM pmag_gui[2783]: ImportError: dlopen(/Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/pmag_gui.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Library not loaded: @rpath/lib/libwx_osx_cocoau-3.0.dylib
1/26/16 9:36:14.546 PM pmag_gui[2783]:   Referenced from: /Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/pmag_gui.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so
1/26/16 9:36:14.546 PM pmag_gui[2783]:   Reason: image not found
1/26/16 9:36:14.684 PM pmag_gui[2783]: pmag_gui Error
```

```
1/26/16 9:37:17.112 PM magic_gui[2796]: -I- Importing MagIC GUI dependencies
1/26/16 9:37:17.647 PM magic_gui[2796]: Traceback (most recent call last):
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "/Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/magic_gui.app/Contents/Resources/__boot__.py", line 81, in <module>
1/26/16 9:37:17.647 PM magic_gui[2796]:     _run()
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "/Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/magic_gui.app/Contents/Resources/__boot__.py", line 62, in _run
1/26/16 9:37:17.647 PM magic_gui[2796]:     exec(compile(source, path, 'exec'), globals(), globals())
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "/Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/magic_gui.app/Contents/Resources/magic_gui.py", line 12, in <module>
1/26/16 9:37:17.647 PM magic_gui[2796]:     import wx
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "wx/__init__.pyc", line 45, in <module>
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "wx/_core.pyc", line 4, in <module>
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "wx/_core_.pyc", line 14, in <module>
1/26/16 9:37:17.647 PM magic_gui[2796]:   File "wx/_core_.pyc", line 10, in __load
1/26/16 9:37:17.647 PM magic_gui[2796]: ImportError: dlopen(/Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/magic_gui.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Library not loaded: @rpath/lib/libwx_osx_cocoau-3.0.dylib
1/26/16 9:37:17.647 PM magic_gui[2796]:   Referenced from: /Users/Laurentia/Downloads/PmagPy-Standalone-OSX-1.0.3/magic_gui.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so
1/26/16 9:37:17.647 PM magic_gui[2796]:   Reason: image not found
1/26/16 9:37:17.781 PM magic_gui[2796]: magic_gui Error
1/26/16 9:37:17.781 PM magic_gui[2796]: 2016-01-26 21:37:17.780 magic_gui[2796:307755] magic_gui Error
```

**Comment by moonshoes87** [comment]
Thanks — I’ll deal with this later today (I’m visiting my sister so it may be a little slower than usual)

**Comment by moonshoes87** [comment]
This should be working correctly now.  I was experimenting with automating these releases a bit better, and managed to break them in the process.  Let me know if you have any further issues!

**Comment by Swanson-Hysell** [comment]
Excellent. It is working well now. Thanks!

It seems a little intense that the download is more than 200 Mb. It might be worth seeing what can be done to decrease the overall size.
