### ISSUE TITLE
Importing Uniaxial AF

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy-Standalone-OSX#8]
I am unable to convert my file to magic format using PmagPyGui for Mac 4.2.24

I have CIT formatted file with uniaxial AF steps in the Z, X and Y directions, labeled as UAFZ1, UAFX1, UAFX2.  Potentially the issue is that due to the limits on character spaces, the level for each of these UAF steps is "hidden" in the specimen file.  

The error thrown is 
"Traceback (most recent call last):
  File "dialogs/pmag_gui_dialogs.py", line 1108, in on_okButton
  File "pmagpy/convert_2_magic.py", line 1349, in cit
ValueError: invalid literal for int() with base 10: 'UAF'"

**Comment by moonshoes87** [comment]
Hi @sslotznick -- sorry or the very long delay.  My second daughter was born 4 days before you created this issue, and I have been on maternity leave ever since.  Would it be possible for you to supply a data file with this issue?  PmagPy must be misinterpreting this format, and I would love to get it fixed.

**Comment by sslotznick** [comment]
Hi @moonshoes87, I apologize for the even longer delay.  I switched institutions and then 2020 happened.  I have a student applying uniaxial AF now though so it is relevant again!  I've emailed you the .sam and associated files I had problems importing.

**Comment by sslotznick** [comment]
I learned that Lori isn't with MagIC anymore.  Attached is an example file as a .zip.

[GRMIssue_Ex.zip](https://github.com/PmagPy/PmagPy-Standalone-OSX/files/9725920/GRMIssue_Ex.zip)
